name: Check (Lint, Format, Build)

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: PHP Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun run setup

      - name: Build project
        run: bun run build

      - name: Run Lint
        run: bun run lint

  format:
    name: PHP Formatter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun run setup

      - name: Build project
        run: bun run build

      - name: Run Formatter
        run: bun run format

